trainer:
  game: "SpaceInvadersNoFrameskip-v4"
  render_mode: "rgb_array"
  episodes: 25000
  learning_rate: 1e-4
  gamma: 0.99
  n_memory_episodes: 500
  prefix_name: ""
  folder: "logging/SpaceInvadersNoFrameskip_1e4_llp50_dsp01_bs128_ppo"
  save_gif_every_x_epochs: 500
  batch_size: 128
  EPS_START: 1
  EPS_END: 0.1
  EPS_DECAY: 250
  TAU: 5e-4
  max_episode_len: 1500
  use_ddqn: true
  replaymemory: 25000
  optimizer: null
  per_alpha: 0
  use_scheduler: false
  validate_every_n_episodes: 250
  validate_episodes: 5
  patience: 3
  game_wrapper: null
  visualizer: null
  gif_fps: 20
  update_every_n_steps: 10
  update_target_every_n_steps: 50
  save_diagnostics: 1000
  clip_grad: 0
  save_model_every_n: 5
  reset_options:
    randomize_position: false
  warmup_steps: 5000
  value_network_lr: 1e-4 # for A2C only
  actor_network_lr: 1e-4 # for A2C only
  entropy_coefficient: 0.01 # for A2C only
  input_shape: (11, 12, 12) # for A2C only
  epochs: 150000 # for A2C only
  early_stopping: 30
  ppo: true


atari_game_wrapper:
  resize_img: [80, 105]
  gray_scale: true
  random_envs: 0
  default_start_prob: 0.1
  random_steps_range: [50, 300]
  stack_n_frames: 4
  losing_live_penalty: 50
  initial_frame_skip: 30
  normalize_factor: 255
  frame_skip: 3

conv_layers_params:
  - in_channels: 4
    out_channels: 8
    kernel_size: 5
    stride: 4
    padding: 1
  - in_channels: 8
    out_channels: 16
    kernel_size: 5
    stride: 4
    padding: 1
  - in_channels: 16
    out_channels: 32
    kernel_size: 5
    stride: 2
    padding: 1
  - in_channels: 32
    out_channels: 64
    kernel_size: 5
    stride: 2
    padding: 1

fc_layers:
  - 256